# Generated by Django 3.1.3 on 2020-12-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201202_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='users/img/avatar/DefUser.png/', upload_to='users/avatars'),
        ),
    ]
