# Generated by Django 3.1.2 on 2020-11-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201113_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Something', max_length=30),
            preserve_default=False,
        ),
    ]
