# Generated by Django 3.1.2 on 2020-11-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201113_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='users/img/avatar/DefUser.png', upload_to='users/img/avatar'),
        ),
    ]
