# Generated by Django 3.1.3 on 2020-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_expo_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='users/img/avatar/DefUser.png', upload_to='users/avatars'),
        ),
    ]
