# Generated by Django 3.1.3 on 2020-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201202_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='users/avatars/DefUser.png/', upload_to='users/avatars'),
        ),
    ]
