# Generated by Django 3.1.2 on 2020-10-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
