# Generated by Django 3.1.3 on 2020-12-03 05:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201203_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/orgachat-com/image/upload/v1606966402/o4khxzqguuehfugrx0zt.png', max_length=255, verbose_name='image'),
        ),
    ]
