# Generated by Django 3.1.3 on 2020-11-25 09:27

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201125_0731'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DurationField(default=datetime.datetime(2020, 11, 25, 9, 27, 0, 768496)),
        ),
    ]
