# Generated by Django 3.1.2 on 2020-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_installed',
            field=models.BooleanField(default=False),
        ),
    ]
