# Generated by Django 3.1.2 on 2020-10-23 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=datetime.datetime(2020, 10, 23, 15, 37, 28, 485845, tzinfo=utc), upload_to='users/img/avatar/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default="Hi! I'm an Orgachat user :)", max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
