# Generated by Django 3.1.2 on 2020-10-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='country',
        ),
    ]
