# Generated by Django 3.1.2 on 2020-10-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201023_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/users/img/avatar/DefUser.png/', upload_to='users/img/avatar/'),
        ),
    ]
