# Generated by Django 3.1.2 on 2020-10-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201024_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/img/avatar/DefUser.png/', upload_to='users/img/avatar/'),
        ),
    ]
