# Generated by Django 3.1.2 on 2020-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default="Hi! I'm an Orgachat user :)", max_length=250),
        ),
    ]
