# Generated by Django 3.1.2 on 2020-10-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='someone@gmail.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
