# Generated by Django 3.1.2 on 2020-10-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default="Hi! I'm an Orgachat user", max_length=190, null=True),
        ),
    ]
