# Generated by Django 3.1.2 on 2020-10-24 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_homepagearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearea',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
