# Generated by Django 3.1.2 on 2020-10-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_sub',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
