# Generated by Django 3.1.2 on 2020-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_notif_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notif_sub',
            new_name='sub_auth',
        ),
        migrations.AddField(
            model_name='user',
            name='sub_endpoint',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_p256dh',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
