# Generated by Django 3.1.2 on 2020-10-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20201027_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sub_auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_endpoint',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_p256dh',
        ),
    ]
