# Generated by Django 3.1.2 on 2020-10-28 09:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
