# Generated by Django 3.1.2 on 2020-10-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20201028_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
