# Generated by Django 3.1.2 on 2020-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_temp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_email_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
