# Generated by Django 3.1.2 on 2020-10-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('friend', 'friend'), ('group', 'group')], default='friend', max_length=9),
        ),
    ]
