# Generated by Django 3.1.2 on 2020-10-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='name',
        ),
    ]
