# Generated by Django 3.1.3 on 2020-11-23 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20201120_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_users',
            field=models.ManyToManyField(related_name='read_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
