# Generated by Django 3.1.3 on 2020-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_read_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.FileField(blank=True, default='users/img/avatar/DefUser.png', null=True, upload_to='chat/chat_avatars'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
