# Generated by Django 3.1.3 on 2020-12-03 05:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201203_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
