# Generated by Django 3.1.2 on 2020-11-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201114_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='homepage_area',
        ),
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chat/room/chat_image'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
