# Generated by Django 3.1.2 on 2020-10-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201004_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='message',
            name='area',
        ),
        migrations.AddField(
            model_name='message',
            name='area',
            field=models.ManyToManyField(null=True, to='chat.Area'),
        ),
    ]
