# Generated by Django 3.1.2 on 2020-10-04 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20201004_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='muted_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='area',
            field=models.ManyToManyField(blank=True, to='chat.Area'),
        ),
    ]
