# Generated by Django 3.1.3 on 2020-11-28 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20201128_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_users',
            field=models.ManyToManyField(blank=True, related_name='read_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
