# Generated by Django 3.1.3 on 2020-12-03 05:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20201203_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/orgachat-com/image/upload/v1606966402/o4khxzqguuehfugrx0zt.png', max_length=255, null=True),
        ),
    ]
