# Generated by Django 3.1.2 on 2020-10-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='area',
        ),
        migrations.AddField(
            model_name='message',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.area'),
        ),
    ]
