# Generated by Django 3.1.2 on 2020-10-05 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20201005_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='star_users',
            field=models.ManyToManyField(blank=True, related_name='star_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
