# Generated by Django 3.1.2 on 2020-10-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_homepagearea_date'),
        ('chat', '0011_auto_20201018_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='homepage_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.homepagearea'),
        ),
    ]
