# Generated by Django 3.1.2 on 2020-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_homepagearea_date'),
        ('chat', '0012_room_homepage_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='homepage_area',
        ),
        migrations.AddField(
            model_name='room',
            name='homepage_area',
            field=models.ManyToManyField(to='users.HomepageArea'),
        ),
    ]
