# Generated by Django 3.1.2 on 2020-10-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_homepagearea_date'),
        ('chat', '0013_auto_20201024_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='homepage_area',
            field=models.ManyToManyField(blank=True, to='users.HomepageArea'),
        ),
    ]
