# Generated by Django 3.1.2 on 2020-10-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrothReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypo', models.CharField(max_length=70)),
                ('messages_per_day', models.IntegerField()),
                ('repeat_rate', models.IntegerField()),
                ('new_users_per_day', models.IntegerField()),
            ],
        ),
    ]
