# Generated by Django 3.1.3 on 2020-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthreport',
            old_name='messages_per_day',
            new_name='messages_per_user',
        ),
        migrations.AddField(
            model_name='growthreport',
            name='repeat_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
