# Generated by Django 3.1.2 on 2020-10-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20201029_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthreport',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthreport',
            name='effort',
            field=models.CharField(choices=[('easy', 'easy < 2 day'), ('medium', 'medium > 2day > 4 days'), ('hard', 'hard > 4 days')], default='before', max_length=70),
            preserve_default=False,
        ),
    ]
