# Generated by Django 3.1.2 on 2020-10-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20201029_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthreport',
            name='messages_per_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='growthreport',
            name='new_users_per_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='growthreport',
            name='repeat_rate',
            field=models.FloatField(),
        ),
    ]
